In [1]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

# Load the enviroment
env = gym.make('FrozenLake-v0')

In [4]:
# 테이블을 모두 0으로 초기화한다.
Q = np.zeros([env.observation_space.n,env.action_space.n])
# 한습 매개변수를 설정한다.
lr = .8
y = .95
num_episodes = 2000
# 보상의 총계를 담을 리스트를 생성한다.
rList = []
for i in range(num_episodes):
    # 환경을 리셋하고 첫 번째 새로운 관찰을 얻는다.
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    # 환경을 리셋하고 첫 번째 새로운 관찰을 얻는다.
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    # Q 테이블 학습 알고리즘
    while j < 99:
        j+=1
        # Q 테이블로부터 (노이즈와 함께) 그리디하게 액션을 선택
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        # 환경으로부터 새로운 상태와 보상을 얻는다.
        s1,r,d,_ = env.step(a)
        # 새로운 지식을 통해 Q 테이블을 업데이트한다.
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

# 성공한 에피소드의 비율을 확인 - 즉 보상의 총계를 에피소드 수로 나눔
print("Score over time: "+str(sum(rList)/num_episodes))
# Q 테이블의 모든 값을 출력
print("Final Q-Table Values")
print(Q)

Score over time: 0.5315
Final Q-Table Values
[[8.50351788e-02 0.00000000e+00 1.60734518e-02 1.18710678e-02]
 [1.04207647e-03 1.48409814e-03 5.50636587e-04 1.30507037e-01]
 [4.57402257e-03 1.88265397e-03 1.57312957e-03 2.11817502e-01]
 [0.00000000e+00 1.77281010e-03 0.00000000e+00 6.78188595e-02]
 [1.18611768e-01 6.92975335e-03 1.68819762e-03 1.98138256e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.72547527e-02 8.92603635e-07 1.47433632e-04 3.59467526e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.14119789e-03 0.00000000e+00 0.00000000e+00 3.20568066e-01]
 [0.00000000e+00 3.03350752e-01 6.42314728e-03 0.00000000e+00]
 [2.48966560e-01 1.36653727e-03 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.04485072e-03 1.02488605e-02 5.22241980e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 8.51641255e-01]
 [0.000000