In [96]:
import numpy as np

# 목적: 인공신경망 가중치를 조정하는 방법 
# backpropagation _ XOR
# X: 학습 데이터 변수
# D: 합습 데이터의 정답 변수

# W1: 입력층 - 은닉층 가중치 행렬 변수
# W2: 은닉층 - 출력층 가중치 행렬 변수

# 입력층 2개 노드
# 은닉층 2개 노드
# 출려층 1개 노드
# 활성함수 시그모이드
# Backpropagation algorithm: SGD
# learning rate가 0.9일때 4번째 데이터가 학습이 잘 안되었습니다.
# 비용함수에서 왔다갔다가 많이 이루어진거 같네요
# 앞으로 learning rate는 작게하는게 좋을거 같습니다.

N = 4

def sigmoid(x):
    y = 1/(1+np.exp(-x))
    return y


In [98]:
# 가중치와 학습 데이터를 넘겨받아 새로 갱신된 가중치를 반환합니다.
# W1: 입력층-은닉층 가중치 행렬을 보관하는 변수
# W2: 은닉층-출력층 가중치 행렬을 보관하는 변수
# X: 학습 데이터의 입력 데이터
# D: 학습 데이터의 정답 데이터

lr = 0.2
N = 4

def backkpropagationCE(W1, W2, X, D):        
    for k in range(N):
        x = X[k]
        d = D[k]
        hidden_v = np.matrix([[0.0], [0.0]])
        hidden_y = np.matrix([[0.0], [0.0]])
        hidden_delta = np.matrix([[0.0], [0.0]])
        output_v = np.matrix([[0.0]])
        output_y = np.matrix([[0.0]])
        output_delta = np.matrix([[0.0]])
        
        # 학습
        # 입력층 - 은닉층
        hidden_v = np.matmul(W1, np.transpose(x))
        hidden_y = sigmoid(hidden_v)
            
        # 은닉층 - 출력층
        output_v = np.matmul(W2, hidden_y)
        output_y = sigmoid(output_v)
        
        # 오차
        # 출력층
        output_err = d - output_y
        output_delta = output_err
        
        # 은닉층 오차
        hidden_err = np.matmul(np.transpose(W2), output_delta)
        
        # 은닉층 델타
        for i in range(len(hidden_err)): 
            hidden_delta[i] = hidden_y[i]*(1-hidden_y[i])*hidden_err[i]
        
        # 가중치 조정
        # 입력층 - 가중치
        #print(hidden_delta)
        #print(x)
        #print(W1)
        #print()
        for i in range(len(W1)):
            delta_weight1 = lr*np.matmul(hidden_delta[i], x)
            W1[i] = W1[i] + delta_weight1
            
        # 은닉층 - 출력층
        delta_weight2 = lr*np.matmul(output_delta, np.transpose(hidden_y))
        W2 = W2 + delta_weight2
        
    return [W1, W2]

# 학습 데이터를 하나 꺼내 델타 규칙에 따라 가중치 갱신값(dw)을 계산하고, 이 값으로 신경망의 가중치를
# 새로 갱신하는 과정은 
# 은닉층이 있어 신경망의 출력값을 계산할 때 두 번에 걸쳐 sigmoid 함수를 호출하는 점과 다음과 같이 출력 노드의
# 델타를 역전파시켜 은닉 노드들의 델타(delta)를 계산하는 과정이 추가되었습니다.

In [101]:
ran_w1 = np.random.rand(4)
arr_w1 = ran_w1.reshape(2,2)
W1 = np.asmatrix(arr_w1, dtype=float)

ran_w2 = np.random.rand(2)
arr_w2 = ran_w2.reshape(1,2)
W2 = np.asmatrix(arr_w2, dtype=float)

X = np.matrix([[0.0,0.0], [1.0,0.0], [0.0,1.0], [0.0,0.0]], dtype=float)
D = np.matrix([[0.0], [1.0], [1.0], [0.0]], dtype=float)

#input 행렬에 정렬 방법에 따라 훈련 방법이 달라집니다.

for i in range(1000):
    W = backkpropagationCE(W1, W2, X, D)
    W1 = W[0]
    W2 = W[1]
    
for k in range(N):
    x = X[k]
    hidden_v = np.matrix([[0.0], [0.0]])
    hidden_y = np.matrix([[0.0], [0.0]])
    output_v = np.matrix([[0.0]])
    output_y = np.matrix([[0.0]])
        
    # 입력층 - 은닉층
    hidden_v = np.matmul(W1, np.transpose(x))
    hidden_y = sigmoid(hidden_v)

    # 은닉층 - 출력층
    output_v = np.matmul(W2, hidden_y)
    output_y = sigmoid(output_v)
    
    print(output_y)

[[0.01922588]]
[[0.98696576]]
[[0.98710146]]
[[0.01922588]]


In [2]:
import numpy as np
import tensorflow as tf

# trainint set
X_train = np.array( [[0,0], [0,1], [1,0], [1,1]])
D_train = np.array( [[0], [1], [1], [0]] )

# placeholder
X = tf.placeholder(tf.float32, [None, 2])
D = tf.placeholder(tf.float32, [None, 1])

# variable
W1 = tf.Variable(tf.truncated_normal([2,2]), dtype=tf.float32)
b1 = tf.Variable(tf.zeros([2]), dtype=tf.float32)
W2 = tf.Variable(tf.truncated_normal([2,1]), dtype=tf.float32)
b2 = tf.Variable(tf.zeros([1]), dtype=tf.float32)

# model
H_V = tf.matmul(X, W1)+b1
H_O = tf.sigmoid(H_V)
O_V = tf.matmul(H_O, W2)+b2
Y = tf.sigmoid(O_V)

learn_rate = 0.1
Cost = tf.reduce_mean(-D*tf.math.log(Y)-(1-D)*tf.math.log(1-Y), 1)
train = tf.train.GradientDescentOptimizer(learn_rate).minimize(Cost)

predict = Y

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(20000):
    _train, _Cost = sess.run([train, Cost], feed_dict={X:X_train, D:D_train})

_predict = sess.run([predict], feed_dict={X:X_train})
print("predict=", _predict)
print("result=", np.array(np.array(_predict)>=0.5, np.int))

predict= [array([[0.00125576],
       [0.99826944],
       [0.998831  ],
       [0.00109024]], dtype=float32)]
result= [[[0]
  [1]
  [1]
  [0]]]


In [68]:
import numpy as np

#A = np.matrix([[0.6,0.4],[0.3,0.8]])
#B = np.matrix([[0.0,0.0], [1.0,0.0], [0.0,1.0], [0.0,0.0]])

#print(A)
#print(B)
#AA = np.matmul(A,B)
#print(AA)
#BB = np.matmul(A,np.transpose(B))
#print(BB)
#print(AA[0])
#print(sigmoid(AA[0]))
#print(AA[1])

# 가중치를 계산하기 위해서는 배열을 매트릭스(행렬)로 변환해서 계산해야 합니다.


#hidden_y = np.matrix([[0.5],[0.5]],[[0.64565631],[0.57444252]],[[0.59868766],[0.68997448]],[[0.5],[0.5]])
#hidden_err = np.matrix([[-0.24425569],[-0.30531962]],[[0.14676514],[0.18345642]],[[0.14316259],[0.17895323]],[[-0.24425569],[-0.30531962]])
hidden_y = np.matrix([[0.5],[0.5]])
hidden_err = np.matrix([[-0.24425569],[-0.30531962]])
hidden_delta = np.matrix([[0.0], [0.0]])

print(hidden_y[0])
print(hidden_y[1])

hidden_delta[0] = hidden_y[0] * hidden_err[0]

print(hidden_delta)



W1 = np.matrix([[0.6, 0.4], [0.3, 0.8]], dtype=float)
weight_change = np.matrix([[0.1, 0.2]], dtype=float)
print(W1[0] + weight_change)


[[0.5]]
[[0.5]]
[[-0.12212784]
 [ 0.        ]]
[[0.7 0.6]]


In [5]:
import numpy as np

a = np.array([10**50,19**50,float('NaN')])
print(a)
#outputs:
#array([100000000000000000000000000000000000000000000000000L,
#   8663234049605954426644038200675212212900743262211018069459689001L,
#   nan], dtype=object)

np.isnan(a.astype(float))
np.isnan(a)

[100000000000000000000000000000000000000000000000000
 8663234049605954426644038200675212212900743262211018069459689001 nan]


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [92]:
W1 = np.matrix([[0.2, 0.3], [0.3, 0.4]], dtype=float)
W2 = np.matrix([[0.3, 0.5]], dtype=float)

print(np.random.rand(4))
ran_w1 = np.random.rand(4)
arr_w1 = ran_w1.reshape(2,2)
W1 = np.asmatrix(arr_w1, dtype=float)
print(W1)

[0.78302763 0.73120593 0.76644475 0.72539535] 1
[[0.37837005 0.01989266]
 [0.87833158 0.38781071]]
