In [51]:
import tensorflow as tf
import numpy as np
from math import exp

# 목적: 인공신경망 가중치를 조정하는 방법 
# backpropagation _ XOR
# X: 학습 데이터 변수
# D: 합습 데이터의 정답 변수

# W1: 입력층 - 은닉층 가중치 행렬 변수
# W2: 은닉층 - 출력층 가중치 행렬 변수

# 입력층 2개 노드
# 은닉층 2개 노드
# 출려층 1개 노드
# 활성함수 시그모이드
# Backpropagation algorithm: SGD
il_num = 2
hl_num = 2
ol_num = 1
lr = 0.9
N = 4
    
def sigmoid(x):
    y = 1/(1+exp(x))
    return y

# 가중치와 학습 데이터를 넘겨받아 새로 갱신된 가중치를 반환합니다.
# W1: 입력층-은닉층 가중치 행렬을 보관하는 변수
# W2: 은닉층-출력층 가중치 행렬을 보관하는 변수
# X: 학습 데이터의 입력 데이터
# D: 학습 데이터의 정답 데이터
def backkpropagationXOR(W1, W2, X, D):        
    for k in range(N):
        x = X[k]
        d = D[k]
        hl_v = np.array([0.0, 0.0])
        hl_o = np.array([0.0, 0.0])
        ol_v = 0.0
        y = 0.0
        d_h = np.array([0.0, 0.0])
        
        # 학습
        # 입력층 - 은닉층
        for i in range(len(W1)):
            for j in range(len(x)):
                hl_v[i] = hl_v[i] + W1[i][j]*x[j]
            hl_o[i] = sigmoid(hl_v[i])
        
        # 은닉층 - 출력층
        for i in range(len(W2)):
            for j in range(len(hl_o)):
                ol_v = ol_v + W2[i][j]*hl_o[j]
        y = sigmoid(ol_v)
        
        # 오차
        # 출력층
        e_o = d - y
        d_o = y*(1-y)*e_o
        
        #print(str(d)+"-"+str(y)+"="+str(e_o))
        
        # 은닉층
        e_h = np.transpose(W2)*d_o
        print(e_h[0][0])
        
        ### 여기 부분... 
        for i in range(len(W1)):
            
            for j in range():
            d_h[i] = hl_o[i]*(1-hl_o[i])*e_h[i]
            d_w_h = lr * d_h[i] * np.transpose(x)[i]
            W1[i] = W1[i] + d_w_h
        
        
        
        for i in range(len(W2)):
            d_w_o = lr * d_o * np.transpose(hl_o)
            W2[i] = W2[i] + d_w_o
        
    return [W1, W2]

# 학습 데이터를 하나 꺼내 델타 규칙에 따라 가중치 갱신값(dw)을 계산하고, 이 값으로 신경망의 가중치를
# 새로 갱신하는 과정은 
# 은닉층이 있어 신경망의 출력값을 계산할 때 두 번에 걸쳐 sigmoid 함수를 호출하는 점과 다음과 같이 출력 노드의
# 델타를 역전파시켜 은닉 노드들의 델타(delta)를 계산하는 과정이 추가되었습니다.

In [52]:
W1 = np.array([[0.6, 0.4], [0.3, 0.8]])
W2 = np.array([[0.4, 0.5]])
X = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
D = np.array([0.0, 1.0, 1.0, 0.0])

for i in range(100):
    W = backkpropagationXOR(W1, W2, X, D)
    W1 = W[0]
    W2 = W[1]
    print("")

    
for k in range(N):
    x = X[k]
    hl_v = np.array([0.0, 0.0])
    hl_o = np.array([0.0, 0.0])
    ol_v = 0.0
    y = 0.0
    
    # 입력층 - 은닉층
    for i in range(len(W1)):
        for j in range(len(x)):
            hl_v[i] = hl_v[i] + W1[i][j]*x[j]
        hl_o[i] = sigmoid(hl_v[i])

    # 은닉층 - 출력층
    for i in range(len(hl_o)):
        ol_v = ol_v + W2[i]*hl_o[i]
    y = sigmoid(ol_v)

    #print(y)
    print("")

-0.03702960430657341
0.05012142347487718
0.05823155241089
-0.04877817725662475

-0.038756219595964536
0.05458771401988242
0.06280690122903214
-0.051515577257142044

-0.04044853259329007
0.05934885174924391
0.06766796600472585
-0.054352722516167594

-0.042087330850171245
0.06441242681035023
0.072818963194902
-0.05728649396112405

-0.043651875959420376
0.06978345596088423
0.07826112503112446
-0.06031334158308891

-0.04512028218634783
0.07546386756046669
0.0839922337856528
-0.0634294743125302

-0.046470025535331055
0.0814520178811406
0.09000622066803952
-0.06663109904324381

-0.047678579638622154
0.08774227788859067
0.09629287123375596
-0.06991470125055393

-0.048724162119192393
0.09432473384125711
0.10283768028665198
-0.07327735376029242

-0.04958656059607736
0.10118504519357983
0.10962189534855643
-0.07671703448586426

-0.05024799297958426
0.10830449803458103
0.1166227779181517
-0.08023292929521278

-0.05069394443829257
0.11566028091196602
0.12381409588618464
-0.0838256935814793

-0.050

IndexError: index 1 is out of bounds for axis 0 with size 1

In [31]:
# tensorflow로 구현한 XOR 해결법
import numpy as np
import tensorflow as tf

# trainint set
X_train = np.array( [[0,0], [0,1], [1,0], [1,1]])
D_train = np.array( [[0], [1], [1], [0]] )

# placeholder
X = tf.placeholder(tf.float32, [None, 2])
D = tf.placeholder(tf.float32, [None, 1])

# variable
W1 = tf.Variable(tf.truncated_normal([2,2]))
b1 = tf.Variable(tf.zeros([2]))
W2 = tf.Variable(tf.truncated_normal([2,1]))
b2 = tf.Variable(tf.zeros([1]), dtype=tf.float32)

# model
H_V = tf.matmul(X, W1)+b1
H_O = tf.sigmoid(H_V)
O_V = tf.matmul(H_O, W2)+b2
Y = tf.sigmoid(O_V)

learn_rate = 0.1
Cost = tf.reduce_mean(tf.reduce_sum(tf.square(Y-D), 1))
train = tf.train.GradientDescentOptimizer(learn_rate).minimize(Cost)

predict = Y

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(10000):
    _train, _Cost = sess.run([train, Cost], feed_dict={X:X_train, D:D_train})
    #print( "cost=", _Cost)    

_predict = sess.run([predict], feed_dict={X:X_train})
print("predict=", _predict)
print("result=", np.array(np.array(_predict)>=0.5, np.int))

predict= [array([[0.16879787],
       [0.82265145],
       [0.82073253],
       [0.2327794 ]], dtype=float32)]
result= [[[0]
  [1]
  [1]
  [0]]]


In [40]:
import numpy as np
from math import exp

#print(np.array( [ [1, 2, 3], [4, 5, 6] ]))

#x  = np.array([1.0, 1.1, 1.2]).reshape((1,3))
#x = np.arange(3).reshape((1,3))
#print(x)
#x_t = np.transpose(x)
#print(x_t)

#print(exp(0))
#y = 1/(1+exp(0.0))


W1 = np.array([[0.6, 0.4], [0.3, 0.8]])
W2 = np.array([[0.4, 0.5]])
X = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
D = np.array([0.0, 1.0, 1.0, 0.0])

print(W1)
print(W2)
print(np.transpose(W1))
print(np.transpose(W2))

[[0.6 0.4]
 [0.3 0.8]]
[[0.4 0.5]]
[[0.6 0.3]
 [0.4 0.8]]
[[0.4]
 [0.5]]
