In [1]:
import numpy as np

lr = 0.2
N = 5

def softmax(x) :
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    
    return y
    
def sigmoid(x):
    y = 1/(1+np.exp(-x))
    
    return y

In [2]:
def multiClass(W1, W2, X, D):
    for k in range(N):
        x = np.asmatrix(X[k])
        d = np.asmatrix(D[k])
        hidden_v = np.asmatrix(np.zeros(50, dtype=float).reshape(50,1))
        hidden_y = np.asmatrix(np.zeros(50, dtype=float).reshape(50,1))
        hidden_delta = np.asmatrix(np.zeros(50, dtype=float).reshape(50,1))
        output_v = np.asmatrix(np.zeros(5, dtype=float).reshape(5,1))
        output_y = np.asmatrix(np.zeros(5, dtype=float).reshape(5,1))
        output_delta = np.asmatrix(np.zeros(5, dtype=float).reshape(5,1))
        
        # 학습
        # 입력층 - 은닉층
        hidden_v = np.matmul(W1, np.transpose(x))
        hidden_y = sigmoid(hidden_v)
        
        # 은닉층 - 출력층
        output_v = np.matmul(W2, hidden_y)
        output_y = softmax(output_v)
        
        # 오차
        # 출력층
        output_err = d.reshape(5,1) - output_y
        
        # 은닉층 오차
        hidden_err = np.matmul(np.transpose(W2), output_delta)
        
        # 은닉층 델타
        for i in range(len(hidden_err)): 
            hidden_delta[i] = hidden_y[i]*(1-hidden_y[i])*hidden_err[i]
            
        # 가중치 조정
        # 입력층 - 가중치
        for i in range(len(W1)):
            delta_weight1 = lr*np.matmul(hidden_delta[i], x)
            W1[i] = W1[i] + delta_weight1
            
        # 은닉층 - 출력층
        delta_weight2 = lr*np.matmul(output_delta, np.transpose(hidden_y))
        W2 = W2 + delta_weight2
        
    return [W1, W2]

In [3]:
X = np.zeros(((N, 5, 5)), dtype=float);
D = np.zeros(((N, 1, 5)), dtype=float);
X[0] = np.array([[0,1,1,0,0],
                 [0,0,1,0,0],
                 [0,0,1,0,0],
                 [0,0,1,0,0],
                 [0,1,1,1,0]])
X[1] = np.array([[1,1,1,1,0],
                 [0,0,0,0,1],
                 [0,1,1,1,0],
                 [1,0,0,0,0],
                 [1,1,1,1,1]])
X[2] = np.array([[1,1,1,1,0],
                 [0,0,0,0,1],
                 [0,1,1,1,0],
                 [0,0,0,0,1],
                 [1,1,1,1,0]])
X[3] = np.array([[0,0,0,1,0],
                 [0,0,1,1,0],
                 [0,1,0,1,0],
                 [1,1,1,1,1],
                 [0,0,0,1,0]])
X[4] = np.array([[1,1,1,1,1],
                 [1,0,0,0,0],
                 [1,1,1,1,0],
                 [0,0,0,0,1],
                 [1,1,1,1,0]])
D = np.array([[1,0,0,0,0],
              [0,1,0,0,0],
              [0,0,1,0,0],
              [0,0,0,1,0],
              [0,0,0,0,1]])

ran_w1 = np.random.rand(1250)
arr_w1 = ran_w1.reshape(50,25)
W1 = np.asmatrix(arr_w1, dtype=float)
ran_w2 = np.random.rand(250)
arr_w2 = ran_w2.reshape(5,50)
W2 = np.asmatrix(arr_w2, dtype=float)

X_reshape = X.reshape(5, 25)
for i in range(10000):
    W = multiClass(W1, W2, X_reshape, D)
    W1 = W[0]
    W2 = W[1]

In [4]:
for k in range(N):
    x = np.asmatrix(X_reshape[k])
    hidden_v = np.asmatrix(np.zeros(50, dtype=float).reshape(50,1))
    hidden_y = np.asmatrix(np.zeros(50, dtype=float).reshape(50,1))
    output_v = np.asmatrix(np.zeros(5, dtype=float).reshape(5,1))
    output_y = np.asmatrix(np.zeros(5, dtype=float).reshape(5,1))
    #print(x)
    # 학습
    # 입력층 - 은닉층
    hidden_v = np.matmul(W1, np.transpose(x))
    hidden_y = sigmoid(hidden_v)

    # 은닉층 - 출력층
    output_v = np.matmul(W2, hidden_y)
    output_y = softmax(output_v)
    
    print(output_y)

[[9.02575608e-03]
 [2.38361252e-04]
 [2.78154855e-02]
 [1.88262640e-01]
 [7.74657757e-01]]
[[7.81159842e-03]
 [1.86113953e-04]
 [2.47801012e-02]
 [1.74417043e-01]
 [7.92805144e-01]]
[[7.81709107e-03]
 [1.87133955e-04]
 [2.48727021e-02]
 [1.74893428e-01]
 [7.92229645e-01]]
[[8.11383909e-03]
 [1.92330265e-04]
 [2.52447599e-02]
 [1.78586447e-01]
 [7.87862623e-01]]
[[7.79324481e-03]
 [1.84633789e-04]
 [2.48874137e-02]
 [1.74326835e-01]
 [7.92807872e-01]]


In [ ]:
# 테스트 부분 
# page 134쪽

In [41]:
import numpy as np

X = np.zeros(((N, 5, 5)), dtype=float);
D = np.zeros(((N, 1, 5)), dtype=float);

X[0] = np.array([[0,0,1,1,0],
                 [0,0,1,1,0],
                 [0,1,0,1,0],
                 [0,0,0,1,0],
                 [0,1,1,1,0]])
X[1] = np.array([[1,1,1,1,0],
                 [0,0,0,0,1],
                 [0,1,1,1,0],
                 [1,0,0,0,1],
                 [1,1,1,1,1]])
X[2] = np.array([[1,1,1,1,0],
                 [0,0,0,0,1],
                 [0,1,1,1,0],
                 [1,0,0,0,1],
                 [1,1,1,1,0]])
X[3] = np.array([[0,1,1,1,0],
                 [0,1,0,0,0],
                 [0,1,1,1,0],
                 [0,0,0,1,0],
                 [0,1,1,1,0]])
X[4] = np.array([[0,1,1,1,1],
                 [0,1,0,0,0],
                 [0,1,1,1,0],
                 [0,0,0,1,0],
                 [1,1,1,1,0]])
X_reshape = X.reshape(5, 25)

for k in range(N):
    x = np.asmatrix(X_reshape[k])
    hidden_v = np.asmatrix(np.zeros(50, dtype=float).reshape(50,1))
    hidden_y = np.asmatrix(np.zeros(50, dtype=float).reshape(50,1))
    output_v = np.asmatrix(np.zeros(5, dtype=float).reshape(5,1))
    output_y = np.asmatrix(np.zeros(5, dtype=float).reshape(5,1))
    
    hidden_v = np.matmul(W1, np.transpose(x))
    hidden_y = sigmoid(hidden_v)
    output_v = np.matmul(W2, hidden_y)
    output_y = softmax(output_v)
    
    print(output_y)

[[2.50978682e-01]
 [2.39599891e-02]
 [1.06704632e-03]
 [7.23837018e-01]
 [1.57264563e-04]]
[[6.55705500e-05]
 [9.95638640e-01]
 [3.72594969e-03]
 [6.59506810e-05]
 [5.03888620e-04]]
[[5.23680107e-04]
 [2.73951569e-02]
 [9.70705343e-01]
 [2.62607315e-05]
 [1.34955875e-03]]
[[0.46076252]
 [0.09211667]
 [0.43877842]
 [0.00716362]
 [0.00117876]]
[[0.00151456]
 [0.25742899]
 [0.23359734]
 [0.00456149]
 [0.50289762]]


In [37]:
import numpy as np
import random

W1 = np.zeros((50, 25))
W2 = np.zeros((5, 50))

for i in range(50):
    for j in range(25):
        W1[i][j] = round(random.uniform(0.1, 1.0),1)
        
for i in range(5):
    for j in range(50):
        W2[i][j] = round(random.uniform(0.1, 1.0),1)

In [36]:
import numpy as np

X = np.zeros(((2, 5, 5)));
D = np.zeros(5)

X[0] = np.array([[0,1,1,0,0],
                 [0,0,1,0,0],
                 [0,0,1,0,0],
                 [0,0,1,0,0],
                 [0,1,1,1,0]])

X[1] = np.array([[1,1,1,1,0],
                 [0,0,0,0,1],
                 [0,1,1,1,0],
                 [1,0,0,0,0],
                 [1,1,1,1,1]])

In [1]:
import numpy as np
Z = np.array([1.0, 1.0, 1.0, 1.0])

def func(TempLake, Z):
    A = TempLake
    B = Z
    return A * B

Nlayers = Z.size
N = 3
TempLake = np.zeros((N + 1, Nlayers))

kOUT = np.zeros(N + 1, dtype=object)
for i in range(N):
    kOUT[i] = func(TempLake[i], Z)
    
# It's a pity that both of the answers figure out the problem but didn't give a conclusion to solve that. Let's see the code.
# The error shows that you set the ith item of kOUT(dtype:int) into a array, every item in kOUT is just a int item, can't point to other datatype, you should change the statement to change the datatype of the kOUT. For example, like:
# Change the statement below:
# kOUT = np.zeros(N + 1) -> kOUT = np.zeros(N + 1, dtype=object) or kOUT = np.zeros((N + 1, N + 1))

In [2]:
import numpy as np
Z=np.array([1.0,1.0,1.0,1.0])  

def func(TempLake,Z):
    A=TempLake
    B=Z
    return A*B

Nlayers=Z.size
N=3
TempLake=np.zeros((N+1,Nlayers))

kOUT=np.zeros(N+1)
for i in range(N):
    kOUT[i]=func(TempLake[i],Z)

ValueError: setting an array element with a sequence.

In [4]:
import numpy as np

x = np.array([[-0.20646505,  0.07763347, -0.16161097,  0.370439  ],
              [-0.91295327,-0.73768934, -0.78909055,  0.06156045],
              [-0.37242104,  0.51828245, -1.16138222, -0.02489585],
              [-1.07890926, -0.29704036, -1.7888618,  -0.3337744 ]],dtype=object)

m = 5
sigma = 1
#np.exp((-(x-m)**2)/(2*sigma)) 
# It maybe because you have your array's dtype as object so convert it to float i.e

# Convert it to float i.e:
#This also depends on the numpy version you are using. You should also try updating numpy, so many bugs have been fixed.
np.exp((-(x.astype(float)-m)**2)/(2*sigma))

array([[1.29935943e-06, 5.47758566e-06, 1.63950875e-06, 2.21778276e-05],
       [2.55786406e-08, 7.10033001e-08, 5.27984133e-08, 5.06026050e-06],
       [5.40131118e-07, 4.34936286e-05, 5.70846640e-09, 3.28945338e-06],
       [9.45644899e-09, 8.07503629e-07, 9.81698210e-11, 6.64271640e-07]])

In [68]:
print(np.zeros(5).reshape(5,1))
B=[[5.13089956e-02],
 [7.95437307e-03],
 [9.39397881e-01],
 [7.65109185e-04],
 [5.73641581e-04]]

print(np.asmatrix(B).reshape(1,5))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[5.13089956e-02 7.95437307e-03 9.39397881e-01 7.65109185e-04
  5.73641581e-04]]


In [ ]:
import numpy as np
import tensorflow as tf

learn_rate = 0.2
# trainint set
X_train = np.matrix([[0.0,0.0], [1.0,0.0], [0.0,1.0], [0.0,0.0]], dtype=float)
D_train = np.matrix([[0.0], [1.0], [1.0], [0.0]], dtype=float)

# placeholder
X = tf.placeholder(tf.float32, [None, 2])
D = tf.placeholder(tf.float32, [None, 1])

# variable
W1 = tf.Variable(tf.truncated_normal([2,2]), dtype=tf.float32)
b1 = tf.Variable(tf.zeros([2]), dtype=tf.float32)
W2 = tf.Variable(tf.truncated_normal([2,1]), dtype=tf.float32)
b2 = tf.Variable(tf.zeros([1]), dtype=tf.float32)

# model
H_V = tf.matmul(X, W1)+b1
H_O = tf.sigmoid(H_V)
O_V = tf.matmul(H_O, W2)+b2
Y = tf.sigmoid(O_V)

Cost = tf.reduce_mean(-D*tf.math.log(Y)-(1-D)*tf.math.log(1-Y), 1)
train = tf.train.GradientDescentOptimizer(learn_rate).minimize(Cost)
predict = Y

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(1000):
    _train, _Cost = sess.run([train, Cost], feed_dict={X:X_train, D:D_train})

_predict = sess.run([predict], feed_dict={X:X_train})
print("predict=", _predict)
print("result=", np.array(np.array(_predict)>=0.5, np.int))