In [3]:
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow')
#Tensor("Const:0", shape(), dtype=string)
# hello는 Tensor라는 자료형이고 상수를 담고있다.
#print(hello)

a = tf.constant(10)
b = tf.constant(20)
c = tf.add(a,b)
con_list = tf.constant([1,2,3,4])

sess = tf.Session()
print(sess.run(hello))
print(sess.run(c))
print(sess.run([a,b,c])) #각각의 요소 출력
print(sess.run(con_list))

sess.close()

b'Hello, TensorFlow'
30
[10, 20, 30]
[1 2 3 4]


In [12]:
import tensorflow as tf

# placeholder 정의
# float32 자료형 2행3열을 가진 a
a = tf.placeholder(tf.int32, [3])
x1=a
sess = tf.Session()

#placeholder에 값을 넣고 실행
#a에 1, 2, 3을 넣는다.
r1 = sess.run(x1, feed_dict={a:[1,2,3]})
#array(2,4,6) 출력됨
print(r1)

# 배열을 두배로 하는 연산 정의
b = tf.constant(2)
# a의 값에 2배가 되도록 설정
x2 = tf.math.multiply(a,b)

r2 = sess.run(x2, feed_dict={a:[1,2,3]})
#array(2,4,6) 출력됨
print(r2)

#None은 갯수가 지정되지 않음 의미
a = tf.placeholder(tf.int32, [None])
x3 = a
x4 = a
r3 = sess.run(x3, feed_dict={a:[1,2,3,4]})
r4 = sess.run(x4, feed_dict={a:[1,2,3,4,5,6,]})
print(r3)
print(r4)

sess.close()

[1 2 3]
[2 4 6]
[1 2 3 4]
[1 2 3 4 5 6]


In [1]:
import tensorflow as tf


# 변수
a = tf.Variable(10)
sess = tf.Session()
sess.run(tf.initialize_all_variables())
print(sess.run(a))
sess.close()

# 정규분포값 만듬
w = tf.Variable(tf.random_normal([3,2]))
sess = tf.Session()
sess.run(tf.initialize_all_variables())
print(sess.run(w))
sess.close()

# 직접 입력도 가능
w2 = tf.Variable([[1.0, 0.1], [0.2, 2.0], [3.0, 3.2]])
sess = tf.Session()
sess.run(tf.initialize_all_variables())
print(sess.run(w2))
sess.close()

# 행렬의 곱
X = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
W = tf.Variable([[0.1,1.0],[0.2,2.0],[0.3, 3.0]])
# 행렬의 자료형은 일치해야 한다. (2,3)*(3,2)
res = tf.matmul(X,W)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(res))
sess.close()

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
10
[[-1.6481068   0.10204522]
 [-1.145536   -0.9159591 ]
 [ 1.7314699  -0.6631014 ]]
[[1.  0.1]
 [0.2 2. ]
 [3.  3.2]]
[[ 1.4000001 14.       ]
 [ 3.2       32.       ]]


In [ ]:
# random package
import tensorflow as tf
sess = tf.Session()

print(sess.run(tf.random.normal(
    shape=[1],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None)))